### ISSUE TITLE
キャッシュによる不整合を解消する仕組みを用意する

### ISSUE THREAD

**Issue by pocketp** [tdtds/massr#121]
html, js, dataそれぞれにバージョン番号を埋め込んで、それぞれのバージョンが分かるようにする。

最新が必要と判断したときには ?t=現在時刻ミリ秒 などを付けたリクエストで再読込するように js で処理し、
そのパラメータがあるときは haml 側でも js や css に同じパラメータを付けてキャッシュが効かないようにする。

バージョン番号を更新忘れなく管理する方法が必要。

**Comment by tdtds** [comment]
#177 にて実装。close.
