### ISSUE TITLE
スマートフォンだと画像表示がサムネイルより小さくなることがある

### ISSUE THREAD

**Issue by pocketp** [tdtds/massr#175]
スタンプ選択でのビュー変更の結果、スマートフォンなど画面幅が狭い場合に投稿画像をタップして表示するとサムネイルよりも小さく表示されることがある。（横向きiPhone5Sスクリーンショットで確認）
もう少し大きく表示されるよう調整する。

PCと合わないならスタイルをMediaで分ける必要があるかも。

**Comment by tdtds** [comment]
これcloseしても良いのでは?  see #179

**Comment by pocketp** [comment]
これ閉じ忘れですね
